# Generated by Django 4.0.6 on 2022-07-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220223_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
