# Generated by Django 4.0.6 on 2022-08-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_p_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='c_email',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='c_email',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='department',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='sem',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
